name: Build and SonarCloud (per-lab)

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

env:
  BUILD_WRAPPER_OUT_DIR: build_wrapper_output_directory
  SONAR_ORG: ekuzm          

jobs:
  build-and-scan:
    name: Build and SonarCloud scans (per-lab)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Build Wrapper
        uses: SonarSource/sonarqube-scan-action/install-build-wrapper@v4

      - name: Run Build Wrapper (generate compile_commands.json)
        run: |
          mkdir -p build
          cmake -S . -B build
          build-wrapper-linux-x86-64 --out-dir ${{ env.BUILD_WRAPPER_OUT_DIR }} cmake --build build/ --config Release

      - name: SonarCloud scan — lab1
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=ekuzm_cpp-labs_lab1
            -Dsonar.organization=${{ env.SONAR_ORG }}
            -Dsonar.projectName=cpp-labs-lab1
            -Dsonar.sources=lab1
            -Dsonar.cfamily.compile-commands=${{ env.BUILD_WRAPPER_OUT_DIR }}/compile_commands.json

      - name: SonarCloud scan — lab2
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=ekuzm_cpp-labs_lab2
            -Dsonar.organization=${{ env.SONAR_ORG }}
            -Dsonar.projectName=cpp-labs-lab2
            -Dsonar.sources=lab2
            -Dsonar.cfamily.compile-commands=${{ env.BUILD_WRAPPER_OUT_DIR }}/compile_commands.json

      - name: SonarCloud scan — lab3
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=ekuzm_cpp-labs_lab3
            -Dsonar.organization=${{ env.SONAR_ORG }}
            -Dsonar.projectName=cpp-labs-lab3
            -Dsonar.sources=lab3
            -Dsonar.cfamily.compile-commands=${{ env.BUILD_WRAPPER_OUT_DIR }}/compile_commands.json

      - name: SonarCloud scan — lab4
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=ekuzm_cpp-labs_lab4
            -Dsonar.organization=${{ env.SONAR_ORG }}
            -Dsonar.projectName=cpp-labs-lab4
            -Dsonar.sources=lab4
            -Dsonar.cfamily.compile-commands=${{ env.BUILD_WRAPPER_OUT_DIR }}/compile_commands.json
