name: Build & SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    env:
      SONAR_ORG: ekuzm

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Build Wrapper
        uses: SonarSource/sonarqube-scan-action/install-build-wrapper@v4

      - name: Build lab1
        run: |
          rm -rf build_lab1
          mkdir build_lab1
          cmake -S lab1 -B build_lab1 -DCMAKE_CXX_FLAGS="--coverage"
          build-wrapper-linux-x86-64 --out-dir build_wrapper_lab1 cmake --build build_lab1 --config Release

      - name: Build lab2
        run: |
          rm -rf build_lab2
          mkdir build_lab2
          cmake -S lab2 -B build_lab2 -DCMAKE_CXX_FLAGS="--coverage"
          build-wrapper-linux-x86-64 --out-dir build_wrapper_lab2 cmake --build build_lab2 --config Release

      - name: Build lab3
        run: |
          rm -rf build_lab3
          mkdir build_lab3
          cmake -S lab3 -B build_lab3 -DCMAKE_CXX_FLAGS="--coverage"
          build-wrapper-linux-x86-64 --out-dir build_wrapper_lab3 cmake --build build_lab3 --config Release

      - name: Build lab4
        run: |
          rm -rf build_lab4
          mkdir build_lab4
          cmake -S lab4 -B build_lab4 -DCMAKE_CXX_FLAGS="--coverage"
          build-wrapper-linux-x86-64 --out-dir build_wrapper_lab4 cmake --build build_lab4 --config Release

      - name: SonarCloud scan lab1
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=ekuzm_cpp-labs_lab1
            -Dsonar.organization=${{ env.SONAR_ORG }}
            -Dsonar.sources=lab1
            -Dsonar.cfamily.compile-commands=build_wrapper_lab1/compile_commands.json

      - name: SonarCloud scan lab2
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=ekuzm_cpp-labs_lab2
            -Dsonar.organization=${{ env
