name: Build and SonarQube Analysis
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [lab1, lab2, lab3, lab4]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Install Build Wrapper
        uses: SonarSource/sonarqube-scan-action/install-build-wrapper@v4
      
      - name: Configure and Build ${{ matrix.project }}
        run: |
          mkdir build-${{ matrix.project }}
          cd build-${{ matrix.project }}
          cmake ../${{ matrix.project }}
          build-wrapper-linux-x86-64 --out-dir ../bw-output-${{ matrix.project }} make
      
      - name: SonarQube Scan for ${{ matrix.project }}
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=ekuzm_ekuzm.cpp-${{ matrix.project }}
            -Dsonar.organization=ekuzm
            -Dsonar.projectName=ekuzm.cpp-${{ matrix.project }}
            -Dsonar.sources=${{ matrix.project }}
            -Dsonar.cfamily.compile-commands=bw-output-${{ matrix.project }}/compile_commands.json